import { useState } from 'react';
import { Link } from 'react-router-dom';
import { X } from 'lucide-react';

const NAV_LINKS = [
  { label: 'Explore',       to: '/explore' },
  { label: 'Services',      to: '/services' },
  { label: 'Pricing',       to: '/pricing' },
  { label: 'Community',     to: '/community' },
  { label: 'Career',        to: '/career' },
  { label: 'Partner with Us', to: '/partner' },
  { label: 'Developers',    to: '/developers' },
];

const CATEGORY_LINKS = [
  'Automate', 'Finance', 'Companion', 'Life Assistant',
  'Community', 'Career', 'Business', 'Creative',
];

const LEGAL_CONTENT = {
  privacy: {
    title: 'Privacy Policy',
    body: `Last updated: January 2026

Havro ("we", "us", or "our") is committed to protecting your privacy. This policy explains how we collect, use, and safeguard your information.

Information We Collect
We collect information you provide directly (name, email, payment details) and data generated by your use of the platform (activity logs, preferences, messages).

How We Use Your Information
Your data is used to provide and improve our services, process payments, send important updates, and personalize your experience. We do not sell your personal data to third parties.

Data Retention
We retain your data for as long as your account is active. You may request deletion at any time by contacting support@havro.app.

Security
We use industry-standard encryption and security practices to protect your data. No method of transmission over the Internet is 100% secure, but we strive to use commercially acceptable means.

Contact Us
If you have questions about this policy, email us at privacy@havro.app.`,
  },
  terms: {
    title: 'Terms of Service',
    body: `Last updated: January 2026

By accessing or using Havro, you agree to be bound by these Terms of Service.

Eligibility
You must be at least 13 years old to use Havro. By using our platform you represent that you meet this requirement.

Acceptable Use
You agree not to misuse our services — including attempting to access systems without authorization, violating laws, or harassing other users.

AI-Generated Content
Havro uses AI to provide guidance and assistance. AI responses are for informational purposes only and do not constitute professional legal, medical, or financial advice.

Payments & Subscriptions
Paid plans are billed in advance on a monthly or yearly basis. Cancellations take effect at the end of the current billing period. No refunds are issued for partial periods.

Limitation of Liability
Havro is provided "as is". We are not liable for indirect, incidental, or consequential damages arising from your use of the platform.

Contact Us
For questions about these terms, email legal@havro.app.`,
  },
};

export default function Footer() {
  const [modal, setModal] = useState(null); // 'privacy' | 'terms' | null

  return (
    <>
      <footer style={s.footer}>
        <div style={s.inner}>
          {/* Top row */}
          <div style={s.topRow}>
            <Link to="/" style={s.logo}>Havro</Link>
            <div style={s.topLinks}>
              {NAV_LINKS.map(({ label, to }) => (
                <FooterLink key={to} to={to}>{label}</FooterLink>
              ))}
            </div>
          </div>

          {/* Middle row */}
          <div style={s.midRow}>
            {CATEGORY_LINKS.map((cat, i) => (
              <span key={cat}>
                <FooterLink to={`/explore?category=${cat.toLowerCase().replace(' ', '-')}`}>
                  {cat}
                </FooterLink>
                {i < CATEGORY_LINKS.length - 1 && (
                  <span className="footer-sep" style={{ color: '#3A3A3A', margin: '0 4px' }}>|</span>
                )}
              </span>
            ))}
          </div>

          {/* Bottom row */}
          <div style={s.borderTop} />
          <div style={s.bottomRow}>
            <span className="footer-copy" style={s.copy}>© 2026 Havro. All rights reserved.</span>
            <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap', alignItems: 'center' }}>
              <button
                className="footer-link"
                onClick={() => setModal('privacy')}
                style={s.legalBtn}
              >
                Privacy Policy
              </button>
              <span className="footer-sep" style={{ color: '#3A3A3A' }}>·</span>
              <button
                className="footer-link"
                onClick={() => setModal('terms')}
                style={s.legalBtn}
              >
                Terms
              </button>
              <span className="footer-sep" style={{ color: '#3A3A3A' }}>·</span>
              <a
                className="footer-link"
                href="mailto:hello@havro.app"
                style={s.legalBtn}
              >
                Contact
              </a>
            </div>
          </div>
        </div>
      </footer>

      {/* Legal modal */}
      {modal && (
        <LegalModal
          title={LEGAL_CONTENT[modal].title}
          body={LEGAL_CONTENT[modal].body}
          onClose={() => setModal(null)}
        />
      )}
    </>
  );
}

function LegalModal({ title, body, onClose }) {
  return (
    <>
      <div
        style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', zIndex: 400 }}
        onClick={onClose}
      />
      <div className="legal-modal" style={s.modal}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '20px' }}>
          <h2 style={{ fontFamily: "'Inter', sans-serif", fontWeight: 700, fontSize: '20px', color: 'var(--text-primary)' }}>
            {title}
          </h2>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '4px', color: 'var(--text-secondary)' }}>
            <X size={20} strokeWidth={1.5} />
          </button>
        </div>
        <div style={{ overflowY: 'auto', maxHeight: 'calc(80vh - 80px)' }}>
          {body.split('\n\n').map((para, i) => (
            para.trim() ? (
              <p key={i} style={{
                fontFamily: "'Inter', sans-serif",
                fontSize: '14px',
                color: 'var(--text-secondary)',
                lineHeight: 1.7,
                marginBottom: '16px',
                fontWeight: para.length < 40 && !para.startsWith('Last') ? 600 : 400,
              }}>
                {para}
              </p>
            ) : null
          ))}
        </div>
      </div>
    </>
  );
}

function FooterLink({ to, children }) {
  return (
    <Link
      to={to}
      className="footer-link"
      style={{ color: '#737373', fontSize: '13px', textDecoration: 'none', transition: 'color 0.18s ease' }}
    >
      {children}
    </Link>
  );
}

const s = {
  footer: {
    background: 'var(--footer-bg)',
    borderTop: '1px solid #2A2A2A',
    paddingTop: '48px',
    paddingBottom: '40px',
  },
  inner: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 48px',
  },
  topRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '16px',
    marginBottom: '32px',
  },
  logo: {
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontSize: '20px',
    letterSpacing: '-0.03em',
    color: '#FFFFFF',
    textDecoration: 'none',
  },
  topLinks: {
    display: 'flex',
    gap: '24px',
    flexWrap: 'wrap',
  },
  midRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '4px',
    marginBottom: '32px',
    fontSize: '13px',
    alignItems: 'center',
  },
  borderTop: {
    borderTop: '1px solid #2A2A2A',
    marginBottom: '24px',
  },
  bottomRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '12px',
  },
  copy: {
    color: '#737373',
    fontSize: '13px',
    fontFamily: "'Inter', sans-serif",
  },
  legalBtn: {
    color: '#737373',
    fontSize: '13px',
    textDecoration: 'none',
    transition: 'color 0.18s ease',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    fontFamily: "'Inter', sans-serif",
  },
  modal: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: 401,
    background: 'var(--bg-card)',
    borderRadius: '16px',
    padding: '32px',
    width: '90%',
    maxWidth: '600px',
    maxHeight: '80vh',
    boxShadow: 'var(--shadow-modal)',
    display: 'flex',
    flexDirection: 'column',
  },
};
